# Generated by Django 3.2.16 on 2024-05-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
